ecurring/woocommerce

- composer.json
- composer.lock
- src/EnvironmentChecker.php
- tests/Unit/EnvironmentCheckerTest.php
- woo-ecurring.php
Addresses [ECUR-46](https://inpsyde.atlassian.net/browse/ECUR-46).
Check if Mollie Payments for Woocommerce plugin is active before initializing the plugin. Don't do anything but add admin notice if Mollie is not active.
Also, add PSR-4 autoloading for new classes.
> Check if Mollie Payments for Woocommerce plugin is active

- includes/ecurring/wc/plugin.php
Addresses [ECUR-44](https://inpsyde.atlassian.net/browse/ECUR-44).
Make Mollie payment methods visible but doesn't make them work. Not sure if this is in scope of this PR.
> Unhide Mollie payment methods

- includes/ecurring/wc/plugin.php
Addresses [ECUR-56](https://inpsyde.atlassian.net/browse/ECUR-56).
Don't save a subscription plan for a product if not selected. Additionally, delete saved subscription plan if not selected but was saved before. 
Update no subscription plan option text and make it translatable.
> Dont add subscription meta field to usual products

- includes/ecurring/wc/plugin.php
Addresses [ECUR-61](https://inpsyde.atlassian.net/browse/ECUR-61).
Not sure if it is the best idea to add even more code to the main plugin class, but I didn't found a better place for it.
> Let mollie payment processing to know if subscription in cart

- includes/ecurring/wc/helper/data.php
- includes/ecurring/wc/helper/settings.php
- includes/ecurring/wc/helper/status.php
- includes/ecurring/wc/plugin.php
- woo-ecurring.php
Addresses [ECUR-53](https://inpsyde.atlassian.net/browse/ECUR-53).
Update required `WC` version. Remove checks for `WC` version < `3.0` and `2.2`. Additionally, remove unused methods, unused method parameters, etc.
> Remove code related to old wc versions

- composer.lock
- src/Api/ApiClient.php
- src/EnvironmentChecker.php
- tests/Unit/EnvironmentCheckerTest.php
- woo-ecurring.php
> Add check for minimum mollie version

- src/AdminPages/AdminController.php
- src/Api/ApiClient.php
- src/EnvironmentChecker.php
- src/EventListener/MolliePaymentEventListener.php
- src/PaymentGatewaysFilter/WhitelistedRecurringPaymentGatewaysFilter.php
- src/Subscription/SubscriptionCrud.php
- src/Subscription/SubscriptionCrudInterface.php
- src/Template/SettingsFormTemplate.php
Addresses [ECUR-52](https://inpsyde.atlassian.net/browse/ECUR-52).
Basically, add return types in the new code where it was missing. I didn't touch the old code because I'm not sure it will work as before and we even have no tests for it.
> Update code to use PHP 7.2 features

- .github/workflows/ci.yml
- composer.json
- composer.lock
- docker/Dockerfile_wp
Addresses [ECUR-68](https://inpsyde.atlassian.net/browse/ECUR-68).
Fix fatal error on `composer install` and `composer update`.
> Fix composer install

- composer.json
- composer.lock
- src/EnvironmentChecker/EnvironmentChecker.php
- tests/Unit/EnvironmentCheckerTest.php
- woo-ecurring.php
Addresses [ECUR-73](https://inpsyde.atlassian.net/browse/ECUR-73).
Use version factory to normalize version number before comparing.
> Fix version comparison

- includes/settings_form_fields.php
- src/AdminPages/AdminController.php
Addresses [ECUR-74](https://inpsyde.atlassian.net/browse/ECUR-74).
Write logs if `Debug Log` option is enabled.
> Fix logging option

- .psalm/autoloader.php
- composer.json
- composer.lock
- src/Api/SubscriptionPlans.php
- src/Customer/MyAccount.php
- src/Subscription/Metabox/Display.php
- src/Subscription/Metabox/Metabox.php
- src/Subscription/PostType.php
- src/WebHook.php
Addresses [ECUR-84](https://inpsyde.atlassian.net/browse/ECUR-84).
Require Woocommerce version 4 or above in `composer.json`.
Additionally, `psalm` and `phpcs` errors fixed.
> Update Woocommerce version

- composer.lock
- src/Customer/MyAccount.php
- src/Subscription/Repository.php
- src/SubscriptionsJob.php
Addresses [ECUR-72](https://inpsyde.atlassian.net/browse/ECUR-72).
Avoid retrieving all existing posts of some type (orders or custom subscription post type) from DB, use WP Meta Query instead to find exactly what is needed. Also, removed duplications of code related to this PR.
> Better way to check if subscription exists

- composer.lock
- src/Subscription/Repository.php
- tests/Unit/Subscription/RepositoryTest.php
Addresses [ECUR-88](https://inpsyde.atlassian.net/browse/ECUR-88).
Skip subscription import if this subscription id is not saved in the local order meta. Log subscriptions import events.
> Dont import subscription without orders

- composer.lock
- includes/ecurring/wc/plugin.php
- src/AdminPages/ProductEditPageController.php
- tests/Unit/AdminPages/ProductEditPageControllerTest.php
- views/admin/product-edit-page/ecurring-tab.php
Addresses [ECUR-82](https://inpsyde.atlassian.net/browse/ECUR-82).
> Add message about api key is required

- composer.json
- composer.lock
- phpunit.xml.dist
- tests/TestCase.php
- tests/Unit/AdminPages/AdminControllerTest.php
- tests/Unit/AdminPages/Form/FormFieldsCollectionBuilderTest.php
- tests/Unit/AdminPages/Form/NonceFieldBuilderTest.php
- tests/Unit/AdminPages/ProductEditPageControllerTest.php
- tests/Unit/Api/ApiClientTest.php
- tests/Unit/Api/CustomersTest.php
- tests/Unit/Api/SubscriptionPlansTest.php
- tests/Unit/DataTest.php
- tests/Unit/EnvironmentCheckerTest.php
- tests/Unit/EventListener/AddToCartValidationEventListenerTest.php
- tests/Unit/EventListener/MollieMandateCreatedEventListenerTest.php
- tests/Unit/EventListener/PaymentCompletedEventListenerTest.php
- tests/Unit/PaymentGatewaysFilter/WhitelistedRecurringPaymentGatewaysFilterTest.php
- tests/Unit/Subscription/RepositoryTest.php
Addresses [ECUR-77](https://inpsyde.atlassian.net/browse/ECUR-77).
> Prepare code for PHP 8

- src/AdminPages/OrderEditPageController.php
Addresses [ECUR-95](https://inpsyde.atlassian.net/browse/ECUR-95).
> Fix renewal order meta box content

- composer.lock
- src/EventListener/MollieMandateCreatedEventListener.php
Addresses [ECUR-96](https://inpsyde.atlassian.net/browse/ECUR-96).
> Fix purchasing subscription with simple product

- composer.lock
- includes/ecurring/wc/helper/data.php
- includes/ecurring/wc/plugin.php
- src/Api/ApiClient.php
- src/Api/ApiClientInterface.php
- src/Api/Customers.php
- src/Api/Subscriptions.php
- src/EventListener/MollieMandateCreatedEventListener.php
- tests/Unit/Api/CustomersTest.php
- tests/Unit/EventListener/MollieMandateCreatedEventListenerTest.php
- woo-ecurring.php
Addresses [ECUR-17](https://inpsyde.atlassian.net/browse/ECUR-17).
Additionally, minor fixes and refactoring.
> Create customer with proper language

- assets/js/ecurring.js
Addresses [ECUR-99](https://inpsyde.atlassian.net/browse/ECUR-99).
Just a small fix.
> Fix undefined AJAX URL

- .psalm/function-stubs.php
- includes/webhook_functions.php
- src/Subscription/PostType.php
Addresses [ECUR-98](https://inpsyde.atlassian.net/browse/ECUR-98).
> Update text fields for subscription post type

- includes/webhook_functions.php
Addresses [ECUR-97](https://inpsyde.atlassian.net/browse/ECUR-97).
> Fix renewal order price

- src/Subscription/Metabox/Display.php
Addresses [ECUR-100](https://inpsyde.atlassian.net/browse/ECUR-100).
Another tiny fix.
> Fix display cancelling date
